### PR TITLE
fixed footer to bottom of page

### PR DESCRIPTION
**Pull request by tonybaldwin**
fixed page footer to the bottom of the page

### CODE REVIEW

**Comment by dbohdan** [comment]
Hi, Tony! Thanks for the pull request. Unfortunately, with just those CSS changes a floating footer does not display correctly: it can overlap page text when scrolling making both the text and itself hard to read.

screenshot-tclssg-pr

Before you invest more effort into this I'd like to ask, why do you think the page footer should be fixed at the bottom of the page? This is not typical of blogs and I'd consider it a hindrance as far as usability goes, especially on mobile.

**Comment by tonybaldwin** [comment]
Reply to this email directly or view it on GitHub.
Well, I just think footers belong on the bottom of the page.
When you have short pages and they footer is in the middle, it looks wrong to me.
See my personal site's design: http://tonybaldwin.me
Although in my footers, I've added space above them to make sure text stays above them.
I could add that, too. I just hadn't thought of it last night when I made those minor edits.
I look forward to looking deeper into tclssg, especially the tcl bits, not just the css/design elements.

**Comment by dbohdan** [comment]
>Well, I just think footers belong on the bottom of the page.
>When you have short pages and they footer is in the middle, it looks wrong to me.

I see. That's fair but I do not think a floating footer *on all pages* is the right solution to this problem; it will look good on short pages at the price of being distracting on the longer, scrolling ones. A better solution would be to change the CSS selectively on just the short pages. You can do this through a page setting (see [page settings](https://github.com/tclssg/tclssg/wiki/Page-settings) in the User's guide) in the page file itself. E.g.,

```Markdown
{
    title {Short page}
    headExtra {
        <style>
            .footer {position:fixed; bottom:0; width: 100%;}
        </style>
    }
}
This is a short page.
```

>I look forward to looking deeper into tclssg, especially the tcl bits, not just the css/design elements.

Great! If you have questions about Tclssg feel free to ask them using the project issues. Since Tclssg in currently in beta after a major overhaul you may well run into bugs. Please report those that you find the same way.

**Comment by dbohdan** [comment]
I've added my proposed solution [to the FAQ](https://github.com/tclssg/tclssg/wiki/FAQ#how-do-i-change-the-css-on-just-some-of-the-pages). If you are satisfied with it I will be closing this issue.

**Pull request closed without merging**
